### ISSUE TITLE
create movie test does not include a director reference

### ISSUE THREAD

**Issue by rsfarzo** [appdev-projects/msm-gui#1]
https://github.com/appdev-projects/msm-gui/blob/52bfafca85e452f80c40b8c21943e7ef1305fde9/spec/features/00_movies_gui_spec.rb#L35

The referenced test creates a movie with only a title field.  Part of this assignment is to display a movie's director name in a movies index view.  There was some surprise among a TA and myself as to why the test was failing yet the assignment solution was correct. The test fails unless there is a test in the view along the lines of:
```
      <% if the_director.present? %>
      <%= the_director.name %>
      <% end %>
```
I can suggest either creating a director in the test, or underscoring a caveat in the instructions for students to create more fail-safe code.

**Comment by bpurinton** [comment]
@rsfarzo Aha! Thanks for the note. Turns out I had already made that change last week and just never pushed it 🙈. Good catch. Updated now.
